spring:
  application:
    name: spring-boot-dubbo-server
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=UTF-8&&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&connectTimeout=0
    username: root
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    open-in-view: true

server:
  port: 8080
demo:
  service:
    version: 1.0.0

dubbo:
  application:
    id: spring-boot-dubbo-server
    name: spring-boot-dubbo-server
    qos-enable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
  registry:
    address: 127.0.0.1:2181
    id: my-registry
    protocol: zookeeper
  scan:
    basePackages: org.spring.springboot.dubbo